using System.Collections.Generic;

namespace LanguageIntegratedQuery
{
    internal class Data
    {
        public List<User> users = new List<User>
            {
                new User(1, "Claybourne", "Bridgett", "cbridgett0@smugmug.com", char.Parse("M"), 22),
                new User(2, "Vincenz", "Tabary", "vtabary1@nsw.gov.au", char.Parse("M"), 73),
                new User(3, "Elana", "Gerlack", "egerlack2@ox.ac.uk", char.Parse("F"), 91),
                new User(4, "Ramonda", "Drains", "rdrains3@ow.ly", char.Parse("F"), 28),
                new User(5, "Daisi", "Rothchild", "drothchild4@cornell.edu", char.Parse("F"), 98),
                new User(6, "Ezri", "Castro", "ecastro5@nps.gov", char.Parse("M"), 69),
                new User(7, "Henri", "MacArthur", "hmacarthur6@imdb.com", char.Parse("M"), 80),
                new User(8, "Cecelia", "Bifield", "cbifield7@fema.gov", char.Parse("F"), 53),
                new User(9, "Lorna", "Swettenham", "lswettenham8@fastcompany.com", char.Parse("F"), 82),
                new User(10, "King", "Surridge", "ksurridge9@tuttocitta.it", char.Parse("M"), 13),
                new User(11, "Karon", "Amort", "kamorta@alibaba.com", char.Parse("F"), 18),
                new User(12, "Clark", "Blackbourn", "cblackbournb@wired.com", char.Parse("M"), 75),
                new User(13, "Ashbey", "Mham", "amalehamc@eepurl.com", char.Parse("M"), 15),
                new User(14, "Bill", "Humphery", "bhumpheryd@omniture.com", char.Parse("M"), 67),
                new User(15, "Beryl", "Tildesley", "btildesleye@pagesperso-orange.fr", char.Parse("F"), 42),
                new User(16, "Shirlee", "Etteridge", "setteridgef@bluehost.com", char.Parse("F"), 74),
                new User(17, "Ashton", "Weeden", "aweedeng@hatena.ne.jp", char.Parse("M"), 23),
                new User(18, "Pedro", "Ronchka", "pronchkah@mediafire.com", char.Parse("M"), 19),
                new User(19, "Innis", "Tench", "itenchi@ehow.com", char.Parse("M"), 55),
                new User(20, "Pooh", "Hilldrup", "philldrupj@delicious.com", char.Parse("M"), 48),
                new User(21, "Onofredo", "Timby", "otimbyk@gov.uk", char.Parse("M"), 31),
                new User(22, "Tomkin", "Craney", "tcraneyl@hp.com", char.Parse("M"), 65),
                new User(23, "Lorianne", "Scinelli", "lscinellim@pbs.org", char.Parse("F"), 4),
                new User(24, "Matthaeus", "Kirton", "mkirtonn@com.com", char.Parse("M"), 69),
                new User(25, "Gilly", "Bagge", "gbaggeo@eventbrite.com", char.Parse("F"), 23),
                new User(26, "Sax", "Ropars", "sroparsp@delicious.com", char.Parse("M"), 86),
                new User(27, "Fania", "Langton", "flangtonq@cdbaby.com", char.Parse("F"), 21),
                new User(28, "Pauline", "Alans", "palansr@tamu.edu", char.Parse("F"), 30),
                new User(29, "Grazia", "Handslip", "ghandslips@aol.com", char.Parse("F"), 7),
                new User(30, "Eliot", "Feckey", "efeckeyt@vk.com", char.Parse("M"), 45),
                new User(31, "Chelsea", "Castelijn", "ccastelijnu@comsenz.com", char.Parse("F"), 86),
                new User(32, "Blinny", "Fierman", "bfiermanv@abc.net.au", char.Parse("F"), 41),
                new User(33, "Rachel", "Cronchey", "rcroncheyw@freewebs.com", char.Parse("F"), 20),
                new User(34, "Becka", "Lattimer", "blattimerx@senate.gov", char.Parse("F"), 3),
                new User(35, "Yorke", "Patise", "ypatisey@boston.com", char.Parse("M"), 18),
                new User(36, "Nicolle", "Rylands", "nrylandsz@army.mil", char.Parse("F"), 52),
                new User(37, "Ava", "Roxby", "aroxby10@eventbrite.com", char.Parse("F"), 67),
                new User(38, "Roberto", "Cringle", "rcringle11@over-blog.com", char.Parse("M"), 46),
                new User(39, "Dyan", "Blannin", "dblannin12@vkontakte.ru", char.Parse("F"), 42),
                new User(40, "Yankee", "Cursons", "ycursons13@clickbank.net", char.Parse("M"), 7),
                new User(41, "Zonnya", "Reck", "zreck14@parallels.com", char.Parse("F"), 96),
                new User(42, "Currie", "Stansby", "cstansby15@loc.gov", char.Parse("M"), 78),
                new User(43, "Hubie", "Humbell", "hhumbell16@va.gov", char.Parse("M"), 45),
                new User(44, "Barrie", "Tesche", "btesche17@apache.org", char.Parse("M"), 79),
                new User(45, "Marge", "Andrichak", "mandrichak18@mediafire.com", char.Parse("F"), 49),
                new User(46, "Jose", "Thake", "jthake19@goo.gl", char.Parse("M"), 73),
                new User(47, "Denny", "Vannah", "dvannah1a@google.pl", char.Parse("F"), 37),
                new User(48, "Garth", "Sheldon", "gsheldon1b@yellowbook.com", char.Parse("M"), 46),
                new User(49, "Zulema", "Josskowitz", "zjosskowitz1c@photobucket.com", char.Parse("F"), 14),
                new User(50, "Frieda", "Lathaye", "flathaye1d@github.io", char.Parse("F"), 41),
                new User(51, "Beret", "Paliser", "bpaliser1e@eepurl.com", char.Parse("F"), 83),
                new User(52, "Oriana", "Daymond", "odaymond1f@smh.com.au", char.Parse("F"), 71),
                new User(53, "Morganica", "Newbury", "mnewbury1g@cdc.gov", char.Parse("F"), 20),
                new User(54, "Sheffy", "Archibold", "sarchibold1h@ca.gov", char.Parse("M"), 14),
                new User(55, "Susy", "Gooch", "sgooch1i@wordpress.com", char.Parse("F"), 54),
                new User(56, "Nigel", "Melling", "nmelling1j@mapy.cz", char.Parse("M"), 39),
                new User(57, "Salvatore", "Mutimer", "smutimer1k@uol.com.br", char.Parse("M"), 74),
                new User(58, "Vernor", "Hallick", "vhallick1l@stanford.edu", char.Parse("M"), 2),
                new User(59, "Michell", "Westpfel", "mwestpfel1m@scribd.com", char.Parse("F"), 54),
                new User(60, "Linell", "Blockley", "lblockley1n@mysql.com", char.Parse("F"), 93),
                new User(61, "Nettle", "Benini", "nbenini1o@craigslist.org", char.Parse("F"), 32),
                new User(62, "Norene", "Jeays", "njeays1p@drupal.org", char.Parse("F"), 63),
                new User(63, "Jozef", "Elderton", "jelderton1q@apache.org", char.Parse("M"), 7),
                new User(64, "Mirilla", "Basire", "mbasire1r@telegraph.co.uk", char.Parse("F"), 12),
                new User(65, "Rubi", "Eleshenar", "releshenar1s@arstechnica.com", char.Parse("F"), 71),
                new User(66, "Neill", "Caplan", "ncaplan1t@nifty.com", char.Parse("M"), 37),
                new User(67, "Ricard", "Trillo", "rtrillo1u@usgs.gov", char.Parse("M"), 39),
                new User(68, "Lind", "Feary", "lfeary1v@blogspot.com", char.Parse("M"), 12),
                new User(69, "Elga", "McGonigle", "emcgonigle1w@freewebs.com", char.Parse("F"), 4),
                new User(70, "Lelia", "Moody", "lmoody1x@uiuc.edu", char.Parse("F"), 86),
                new User(71, "Roz", "Lardier", "rlardier1y@nature.com", char.Parse("F"), 81),
                new User(72, "Portia", "Callow", "pcallow1z@amazon.co.uk", char.Parse("F"), 34),
                new User(73, "Berkie", "Spellsworth", "bspellsworth20@hubpages.com", char.Parse("M"), 54),
                new User(74, "Matias", "Gaylard", "mgaylard21@multiply.com", char.Parse("M"), 62),
                new User(75, "Lanie", "Halloway", "lhalloway22@arizona.edu", char.Parse("F"), 45),
                new User(76, "Hildegarde", "Whitfield", "hwhitfield23@pagesperso-orange.fr", char.Parse("F"), 64),
                new User(77, "Dinah", "Benedick", "dbenedick24@europa.eu", char.Parse("F"), 5),
                new User(78, "Reilly", "Mascall", "rmascall25@netlog.com", char.Parse("M"), 45),
                new User(79, "Georgie", "Iacomettii", "giacomettii26@ezinearticles.com", char.Parse("M"), 42),
                new User(80, "Amery", "Deerness", "adeerness27@dedecms.com", char.Parse("M"), 39),
                new User(81, "Katlin", "Klimsch", "kklimsch28@macromedia.com", char.Parse("F"), 50),
                new User(82, "Faunie", "Firsby", "ffirsby29@1und1.de", char.Parse("F"), 12),
                new User(83, "Tillie", "Carsey", "tcarsey2a@geocities.com", char.Parse("F"), 4),
                new User(84, "Monique", "Leavesley", "mleavesley2b@telegraph.co.uk", char.Parse("F"), 96),
                new User(85, "Raimund", "East", "reast2c@economist.com", char.Parse("M"), 44),
                new User(86, "Law", "Dugald", "ldugald2d@ihg.com", char.Parse("M"), 87),
                new User(87, "Esdras", "Atton", "eatton2e@msu.edu", char.Parse("M"), 66),
                new User(88, "Judah", "Haddrell", "jhaddrell2f@chron.com", char.Parse("M"), 42),
                new User(89, "Noemi", "McGillicuddy", "nmcgillicuddy2g@addthis.com", char.Parse("F"), 66),
                new User(90, "Gunther", "Wicks", "gwicks2h@buzzfeed.com", char.Parse("M"), 45),
                new User(91, "Evan", "Hartwell", "ehartwell2i@ustream.tv", char.Parse("M"), 10),
                new User(92, "Scarface", "Casillas", "scasillas2j@pinterest.com", char.Parse("M"), 96),
                new User(93, "Irvine", "Fison", "ifison2k@deliciousdays.com", char.Parse("M"), 73),
                new User(94, "L,urette", "Sewall", "lsewall2l@canalblog.com", char.Parse("F"), 14),
                new User(95, "Sada", "Cordingley", "scordingley2m@squarespace.com", char.Parse("F"), 25),
                new User(96, "Blythe", "Witham", "bwitham2n@toplist.cz", char.Parse("F"), 82),
                new User(98, "Gray", "Squelch", "gsquelch2p@wix.com", char.Parse("M"), 61),
                new User(99, "Garwin", "McGeown", "gmcgeown2q@shinystat.com", char.Parse("M"), 12),
                new User(100, "Anna-maria", "Aitken", "aaitken2r@ocn.ne.jp", char.Parse("F"), 25)
            };

        public List<Film> films = new List<Film>
        {
            new Film(1, "Last Emperor, The"),
            new Film(2, "Club Fed"),
            new Film(3, "Sunday Day in Hell, A (En forårsdag i Helvede)"),
            new Film(4, "Guy X"),
            new Film(5, "Dennis the Menace"),
            new Film(6, "She Creature (Mermaid Chronicles Part 1: She Creature)"),
            new Film(7, "The Anderssons in Greece: All Inclusive"),
            new Film(8, "Ikiru"),
            new Film(9, "Amour fou, L'"),
            new Film(10, "Rob Roy"),
            new Film(11, "Adventures of Picasso, The (Picassos äventyr)"),
            new Film(12, "Flame of New Orleans, The"),
            new Film(13, "Under Suspicion"),
            new Film(14, "Center Stage (Ruan Lingyu) (Actress, The) (New China Woman, The)"),
            new Film(15, "Warriors of Virtue"),
            new Film(16, "Dangerous Liaisons"),
            new Film(17, "Kiss for Corliss, A (Almost a Bride)"),
            new Film(18, "God's Country"),
            new Film(19, "Play It Again, Sam"),
            new Film(20, "Wolf Man, The"),
            new Film(21, "Allotment Wives"),
            new Film(22, "Twist of Faith"),
            new Film(23, "Epic"),
            new Film(24, "Juarez"),
            new Film(25, "Hellboy"),
            new Film(26, "Torch Song Trilogy"),
            new Film(27, "Transylvania 6-5000"),
            new Film(28, "Nina Frisk"),
            new Film(29, "Born on the Fourth of July"),
            new Film(30, "This Land Is Mine"),
            new Film(31, "Ice Rink, The (La patinoire)"),
            new Film(32, "Outrageous Fortune"),
            new Film(33, "Ted Bundy"),
            new Film(34, "Fast & Furious (Fast and the Furious 4, The)"),
            new Film(35, "Across the Universe"),
            new Film(36, "Spite Marriage"),
            new Film(37, "Woman Rebels, A (Portrait of a Rebel)"),
            new Film(38, "Never Play Clever Again (Gendarme et les gendarmettes, Le)"),
            new Film(39, "Moon Warriors, The (Zhan shen chuan shuo)"),
            new Film(40, "Abbott and Costello Meet Dr. Jekyll and Mr. Hyde"),
            new Film(41, "Narco Cultura"),
            new Film(42, "Foreverland"),
            new Film(43, "2LDK"),
            new Film(44, "Comedy, The"),
            new Film(45, "Every Girl Should Be Married"),
            new Film(46, "American Pastime"),
            new Film(47, "Lucky One, The"),
            new Film(48, "Final Analysis"),
            new Film(49, "Unfaithful Wife, The (Femme infidèle, La)"),
            new Film(50, "Well Spent Life, A"),
            new Film(51, "Late Shift, The"),
            new Film(52, "Stoker"),
            new Film(53, "Film ist. 7-12"),
            new Film(54, "Wonderland"),
            new Film(55, "An Alligator Named Daisy"),
            new Film(56, "Cherry Crush"),
            new Film(57, "Vai~E~Vem"),
            new Film(58, "Diggstown"),
            new Film(59, "Dr. Dolittle"),
            new Film(60, "Cream Lemon (Kurîmu remon)"),
            new Film(61, "Jetsons: The Movie"),
            new Film(62, "Carmina or Blow Up (Carmina o revienta)"),
            new Film(63, "Incident at Oglala"),
            new Film(64, "W.R.: Mysteries of the Organism"),
            new Film(65, "Liquid Sky"),
            new Film(66, "Comic Book: The Movie"),
            new Film(67, "Iron Horse, The"),
            new Film(68, "Robin Hood: Prince of Thieves"),
            new Film(69, "Seventh Heaven"),
            new Film(70, "Outrage (Autoreiji)"),
            new Film(71, "Taxi"),
            new Film(72, "Unearthly, The"),
            new Film(73, "Night of the Living Dorks"),
            new Film(74, "Luther"),
            new Film(75, "Screwed in Tallinn (Torsk på Tallinn - En liten film om ensamhet)"),
            new Film(76, "Red Dawn"),
            new Film(77, "Beware of a Holy Whore (Warnung vor einer heiligen Nutte)"),
            new Film(78, "Sarraounia"),
            new Film(79, "Power of Kangwon Province, The (Kangwon-do ui him)"),
            new Film(80, "Scavenger Hunt"),
            new Film(81, "Confess"),
            new Film(82, "Tequila Sunrise"),
            new Film(83, "Something from Nothing: The Art of Rap"),
            new Film(84, "Adventures of Pluto Nash, The"),
            new Film(85, "Georg"),
            new Film(86, "Unreasonable Man, An"),
            new Film(87, "King in New York, A"),
            new Film(88, "1911 (Xinhai geming)"),
            new Film(89, "Architect, The"),
            new Film(90, "I Accuse"),
            new Film(91, "Just Anybody (Le premier venu)"),
            new Film(92, "Young Victoria, The"),
            new Film(93, "Fearful Symmetry: The Making of 'To Kill a Mockingbird'"),
            new Film(94, "Under the Skin"),
            new Film(95, "$9.99"),
            new Film(96, "Death Race 2"),
            new Film(97, "Hell in the Pacific"),
            new Film(98, "Finder's Fee"),
            new Film(99, "Poison"),
            new Film(100, "Simple Life of Noah Dearborn, The")
        };

        public List<Student> students = new List<Student>
    {
        new Student {FirstName = "Terry", LastName = "Adams", ID = 120,
            Year = GradeLevel.SecondYear,
            ExamScores = new List<int>{ 99, 82, 81, 79}},
        new Student {FirstName = "Fadi", LastName = "Fakhouri", ID = 116,
            Year = GradeLevel.ThirdYear,
            ExamScores = new List<int>{ 99, 86, 90, 94}},
        new Student {FirstName = "Hanying", LastName = "Feng", ID = 117,
            Year = GradeLevel.FirstYear,
            ExamScores = new List<int>{ 93, 92, 80, 87}},
        new Student {FirstName = "Cesar", LastName = "Garcia", ID = 114,
            Year = GradeLevel.FourthYear,
            ExamScores = new List<int>{ 97, 89, 85, 82}},
        new Student {FirstName = "Debra", LastName = "Garcia", ID = 115,
            Year = GradeLevel.ThirdYear,
            ExamScores = new List<int>{ 35, 72, 91, 70}},
        new Student {FirstName = "Hugo", LastName = "Garcia", ID = 118,
            Year = GradeLevel.SecondYear,
            ExamScores = new List<int>{ 92, 90, 83, 78}},
        new Student {FirstName = "Sven", LastName = "Mortensen", ID = 113,
            Year = GradeLevel.FirstYear,
            ExamScores = new List<int>{ 88, 94, 65, 91}},
        new Student {FirstName = "Claire", LastName = "O'Donnell", ID = 112,
            Year = GradeLevel.FourthYear,
            ExamScores = new List<int>{ 75, 84, 91, 39}},
        new Student {FirstName = "Svetlana", LastName = "Omelchenko", ID = 111,
            Year = GradeLevel.SecondYear,
            ExamScores = new List<int>{ 97, 92, 81, 60}},
        new Student {FirstName = "Lance", LastName = "Tucker", ID = 119,
            Year = GradeLevel.ThirdYear,
            ExamScores = new List<int>{ 68, 79, 88, 92}},
        new Student {FirstName = "Michael", LastName = "Tucker", ID = 122,
            Year = GradeLevel.FirstYear,
            ExamScores = new List<int>{ 94, 92, 91, 91}},
        new Student {FirstName = "Eugene", LastName = "Zabokritski", ID = 121,
            Year = GradeLevel.FourthYear,
            ExamScores = new List<int>{ 96, 85, 91, 60}}
    };

        public Data()
        {
        }
    }

    internal class Film
    {
        public int FilmID { get; set; }
        public string FilmTitle { get; set; }

        public Film(int id, string Title)
        {
            FilmID = id;
            FilmTitle = Title;
        }
    }

    public enum GradeLevel { FirstYear = 1, SecondYear, ThirdYear, FourthYear };

    internal class Student
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ID { get; set; }
        public GradeLevel Year;
        public List<int> ExamScores;
    }
}