using System.Collections.Generic;

namespace LanguageIntegratedQuery
{
    internal class Data
    {
        public List<User> users;
        public Data()
        {
            users = new List<User>
            {
                new User(1, "Claybourne", "Bridgett", "cbridgett0@smugmug.com", char.Parse("M")),
                new User(2, "Vincenz", "Tabary", "vtabary1@nsw.gov.au", char.Parse("M")),
                new User(3, "Elana", "Gerlack", "egerlack2@ox.ac.uk", char.Parse("F")),
                new User(4, "Ramonda", "Drains", "rdrains3@ow.ly", char.Parse("F")),
                new User(5, "Daisi", "Rothchild", "drothchild4@cornell.edu", char.Parse("F")),
                new User(6, "Ezri", "Castro", "ecastro5@nps.gov", char.Parse("M")),
                new User(7, "Henri", "MacArthur", "hmacarthur6@imdb.com", char.Parse("M")),
                new User(8, "Cecelia", "Bifield", "cbifield7@fema.gov", char.Parse("F")),
                new User(9, "Lorna", "Swettenham", "lswettenham8@fastcompany.com", char.Parse("F")),
                new User(10, "King", "Surridge", "ksurridge9@tuttocitta.it", char.Parse("M")),
                new User(11, "Karon", "Amort", "kamorta@alibaba.com", char.Parse("F")),
                new User(12, "Clark", "Blackbourn", "cblackbournb@wired.com", char.Parse("M")),
                new User(13, "Ashbey", "Mham", "amalehamc@eepurl.com", char.Parse("M")),
                new User(14, "Bill", "Humphery", "bhumpheryd@omniture.com", char.Parse("M")),
                new User(15, "Beryl", "Tildesley", "btildesleye@pagesperso-orange.fr", char.Parse("F")),
                new User(16, "Shirlee", "Etteridge", "setteridgef@bluehost.com", char.Parse("F")),
                new User(17, "Ashton", "Weeden", "aweedeng@hatena.ne.jp", char.Parse("M")),
                new User(18, "Pedro", "Ronchka", "pronchkah@mediafire.com", char.Parse("M")),
                new User(19, "Innis", "Tench", "itenchi@ehow.com", char.Parse("M")),
                new User(20, "Pooh", "Hilldrup", "philldrupj@delicious.com", char.Parse("M")),
                new User(21, "Onofredo", "Timby", "otimbyk@gov.uk", char.Parse("M")),
                new User(22, "Tomkin", "Craney", "tcraneyl@hp.com", char.Parse("M")),
                new User(23, "Lorianne", "Scinelli", "lscinellim@pbs.org", char.Parse("F")),
                new User(24, "Matthaeus", "Kirton", "mkirtonn@com.com", char.Parse("M")),
                new User(25, "Gilly", "Bagge", "gbaggeo@eventbrite.com", char.Parse("F")),
                new User(26, "Sax", "Ropars", "sroparsp@delicious.com", char.Parse("M")),
                new User(27, "Fania", "Langton", "flangtonq@cdbaby.com", char.Parse("F")),
                new User(28, "Pauline", "Alans", "palansr@tamu.edu", char.Parse("F")),
                new User(29, "Grazia", "Handslip", "ghandslips@aol.com", char.Parse("F")),
                new User(30, "Eliot", "Feckey", "efeckeyt@vk.com", char.Parse("M")),
                new User(31, "Chelsea", "Castelijn", "ccastelijnu@comsenz.com", char.Parse("F")),
                new User(32, "Blinny", "Fierman", "bfiermanv@abc.net.au", char.Parse("F")),
                new User(33, "Rachel", "Cronchey", "rcroncheyw@freewebs.com", char.Parse("F")),
                new User(34, "Becka", "Lattimer", "blattimerx@senate.gov", char.Parse("F")),
                new User(35, "Yorke", "Patise", "ypatisey@boston.com", char.Parse("M")),
                new User(36, "Nicolle", "Rylands", "nrylandsz@army.mil", char.Parse("F")),
                new User(37, "Ava", "Roxby", "aroxby10@eventbrite.com", char.Parse("F")),
                new User(38, "Roberto", "Cringle", "rcringle11@over-blog.com", char.Parse("M")),
                new User(39, "Dyan", "Blannin", "dblannin12@vkontakte.ru", char.Parse("F")),
                new User(40, "Yankee", "Cursons", "ycursons13@clickbank.net", char.Parse("M")),
                new User(41, "Zonnya", "Reck", "zreck14@parallels.com", char.Parse("F")),
                new User(42, "Currie", "Stansby", "cstansby15@loc.gov", char.Parse("M")),
                new User(43, "Hubie", "Humbell", "hhumbell16@va.gov", char.Parse("M")),
                new User(44, "Barrie", "Tesche", "btesche17@apache.org", char.Parse("M")),
                new User(45, "Marge", "Andrichak", "mandrichak18@mediafire.com", char.Parse("F")),
                new User(46, "Jose", "Thake", "jthake19@goo.gl", char.Parse("M")),
                new User(47, "Denny", "Vannah", "dvannah1a@google.pl", char.Parse("F")),
                new User(48, "Garth", "Sheldon", "gsheldon1b@yellowbook.com", char.Parse("M")),
                new User(49, "Zulema", "Josskowitz", "zjosskowitz1c@photobucket.com", char.Parse("F")),
                new User(50, "Frieda", "Lathaye", "flathaye1d@github.io", char.Parse("F")),
                new User(51, "Beret", "Paliser", "bpaliser1e@eepurl.com", char.Parse("F")),
                new User(52, "Oriana", "Daymond", "odaymond1f@smh.com.au", char.Parse("F")),
                new User(53, "Morganica", "Newbury", "mnewbury1g@cdc.gov", char.Parse("F")),
                new User(54, "Sheffy", "Archibold", "sarchibold1h@ca.gov", char.Parse("M")),
                new User(55, "Susy", "Gooch", "sgooch1i@wordpress.com", char.Parse("F")),
                new User(56, "Nigel", "Melling", "nmelling1j@mapy.cz", char.Parse("M")),
                new User(57, "Salvatore", "Mutimer", "smutimer1k@uol.com.br", char.Parse("M")),
                new User(58, "Vernor", "Hallick", "vhallick1l@stanford.edu", char.Parse("M")),
                new User(59, "Michell", "Westpfel", "mwestpfel1m@scribd.com", char.Parse("F")),
                new User(60, "Linell", "Blockley", "lblockley1n@mysql.com", char.Parse("F")),
                new User(61, "Nettle", "Benini", "nbenini1o@craigslist.org", char.Parse("F")),
                new User(62, "Norene", "Jeays", "njeays1p@drupal.org", char.Parse("F")),
                new User(63, "Jozef", "Elderton", "jelderton1q@apache.org", char.Parse("M")),
                new User(64, "Mirilla", "Basire", "mbasire1r@telegraph.co.uk", char.Parse("F")),
                new User(65, "Rubi", "Eleshenar", "releshenar1s@arstechnica.com", char.Parse("F")),
                new User(66, "Neill", "Caplan", "ncaplan1t@nifty.com", char.Parse("M")),
                new User(67, "Ricard", "Trillo", "rtrillo1u@usgs.gov", char.Parse("M")),
                new User(68, "Lind", "Feary", "lfeary1v@blogspot.com", char.Parse("M")),
                new User(69, "Elga", "McGonigle", "emcgonigle1w@freewebs.com", char.Parse("F")),
                new User(70, "Lelia", "Moody", "lmoody1x@uiuc.edu", char.Parse("F")),
                new User(71, "Roz", "Lardier", "rlardier1y@nature.com", char.Parse("F")),
                new User(72, "Portia", "Callow", "pcallow1z@amazon.co.uk", char.Parse("F")),
                new User(73, "Berkie", "Spellsworth", "bspellsworth20@hubpages.com", char.Parse("M")),
                new User(74, "Matias", "Gaylard", "mgaylard21@multiply.com", char.Parse("M")),
                new User(75, "Lanie", "Halloway", "lhalloway22@arizona.edu", char.Parse("F")),
                new User(76, "Hildegarde", "Whitfield", "hwhitfield23@pagesperso-orange.fr", char.Parse("F")),
                new User(77, "Dinah", "Benedick", "dbenedick24@europa.eu", char.Parse("F")),
                new User(78, "Reilly", "Mascall", "rmascall25@netlog.com", char.Parse("M")),
                new User(79, "Georgie", "Iacomettii", "giacomettii26@ezinearticles.com", char.Parse("M")),
                new User(80, "Amery", "Deerness", "adeerness27@dedecms.com", char.Parse("M")),
                new User(81, "Katlin", "Klimsch", "kklimsch28@macromedia.com", char.Parse("F")),
                new User(82, "Faunie", "Firsby", "ffirsby29@1und1.de", char.Parse("F")),
                new User(83, "Tillie", "Carsey", "tcarsey2a@geocities.com", char.Parse("F")),
                new User(84, "Monique", "Leavesley", "mleavesley2b@telegraph.co.uk", char.Parse("F")),
                new User(85, "Raimund", "East", "reast2c@economist.com", char.Parse("M")),
                new User(86, "Law", "Dugald", "ldugald2d@ihg.com", char.Parse("M")),
                new User(87, "Esdras", "Atton", "eatton2e@msu.edu", char.Parse("M")),
                new User(88, "Judah", "Haddrell", "jhaddrell2f@chron.com", char.Parse("M")),
                new User(89, "Noemi", "McGillicuddy", "nmcgillicuddy2g@addthis.com", char.Parse("F")),
                new User(90, "Gunther", "Wicks", "gwicks2h@buzzfeed.com", char.Parse("M")),
                new User(91, "Evan", "Hartwell", "ehartwell2i@ustream.tv", char.Parse("M")),
                new User(92, "Scarface", "Casillas", "scasillas2j@pinterest.com", char.Parse("M")),
                new User(93, "Irvine", "Fison", "ifison2k@deliciousdays.com", char.Parse("M")),
                new User(94, "L,urette", "Sewall", "lsewall2l@canalblog.com", char.Parse("F")),
                new User(95, "Sada", "Cordingley", "scordingley2m@squarespace.com", char.Parse("F")),
                new User(96, "Blythe", "Witham", "bwitham2n@toplist.cz", char.Parse("F")),
                new User(97, "Legra", "McBratney", "lmcbratney2o@blogspot.com", char.Parse("F")),
                new User(98, "Gray", "Squelch", "gsquelch2p@wix.com", char.Parse("M")),
                new User(99, "Garwin", "McGeown", "gmcgeown2q@shinystat.com", char.Parse("M")),
                new User(100, "Anna-maria", "Aitken", "aaitken2r@ocn.ne.jp", char.Parse("F"))
            };
        }
    }
}